{% set name = "ratarmount" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ratarmount-{{ version }}.tar.gz
  sha256: 7179b7d352cc12c884d5e2893bbd204f2edab1d67908a9cab712e29d6dbe889e
  folder: .
  patches:
    - remove-rapidgzip.patch

build:
  entry_points:
    - ratarmount=ratarmount:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools >=46.4.0
    - wheel
    - pip
  run:
    - python >=3.6
    - ratarmountcore >=0.7,<0.8
    - fusepy
    - indexed_bzip2 >=1.3.1,<2.0
    - indexed_gzip >=1.6.3,<2.0
    - indexed_zstd >=1.3.1,<2.0
    - dataclasses
    - python-xz >=0.4.0,<0.5
    - rarfile >=4.0,<5
    - python-libarchive-c >=5.1,<6

test:
  imports:
    - ratarmount
  commands:
    - pip check
    - ratarmount --help
  requires:
    - pip

about:
  home: https://github.com/mxmlnkn/ratarmount
  summary: Random Access Read-Only Tar Mount
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
    - mxmlnkn
